(dp1
S'output'
p2
S"<type 'exceptions.OSError'> [Errno 2] No such file or directory"
p3
sS'layer'
p4
S'/home/ubuntu/webnettools/web2py/applications/ssllabs/controllers/tools.py'
p5
sS'code'
p6
S'@auth.requires_login()\ndef certhealth():\n    ip_addresses = db().select(db.us_ips.ALL, orderby=db.us_ips.ip_address)\n    return dict(ip_adresses=ip_addresses)\n\n\n@auth.requires_login()\ndef checkports():\n    import ast\n    import os\n    import subprocess\n    db_request = db.us_ips(request.args(0, cast=int, otherwise=URL(\'error\'))) or redirect(URL(\'ssllabs\', \'index\'))\n    ports = db_request[\'open_port\']\n    ports_as_list = ast.literal_eval(ports)\n    #print ports_as_list\n    if 443 in ports_as_list:\n    #   pysslscan_cmd = os.system("pysslscan scan --scan=protocol.http --scan=vuln.heartbleed --scan=server.renegotiation" \\\n    #                     " --scan=server.preferred_ciphers --scan=server.ciphers   --report=term:rating=ssllabs.2009e"\n    #                     " --ssl2 --ssl3 --tls10 --tls11 --tls12 http://" + db_request[\'ip_address\'])\n        pysslscan_cmd = "pysslscan scan --scan=protocol.http --scan=vuln.heartbleed --scan=server.renegotiation" \\\n                        " --scan=server.preferred_ciphers --scan=server.ciphers --report=term" \\\n                        " --ssl2 --ssl3 --tls10 --tls11 --tls12 http://" + db_request[\'ip_address\'] + "> " + \\\n                        request.folder + "private/pysslscan_ascii_esc.tmp"\n    #   print pysslscan_cmd\n        result = subprocess.Popen(pysslscan_cmd, shell=True, stdout=subprocess.PIPE, universal_newlines=True)\n        result_stdout = result.stdout.read()\n        pysslscan_ascii = os.system("sed \'s/\\x1b\\[0m//g\' " + request.folder + "private/pysslscan_ascii_esc.tmp " + \\\n                                    "> " + request.folder + "private/pysslscan_ascii_clean.tmp")\n    #   clean_file = open(request.folder + "private/pysslscan_ascii_clean.tmp", "w")\n    #   clean_file.write(str(pysslscan_ascii))\n    #   clean_file.close()\n        pysslscan_ascii_file = open(request.folder + "private/pysslscan_ascii_clean.tmp", "r")\n    #   remove_tmp_files = os.system("rm -f " + request.folder + "private/pysslscan_ascii*.tmp")\n        return dict(scan_result=pysslscan_ascii_file.read())\n    else:\n        return dict(scan_result="Nothing to report!")\n\n\n@auth.requires_login()\ndef ping():\n    welcome_message_ping = "Welcome to the PING Tool!"\n    return dict(message=welcome_message_ping)\n\n\n@auth.requires_login()\ndef traceroute():\n    import os\n    from subprocess import *\n    form=FORM(\'What IP address to \\\'trace\\\':\',\n                INPUT(_name=\'ipaddress\', requires=IS_IPV4()),\n                INPUT(_type=\'submit\'))\n    if form.process().accepted:\n        session.flash = \'Input accepted\'\n        session.vars=form.vars\n        #trace = os.popen(\'ping \' + \'-c 2 \'+ str(session.vars.ipaddress))\n        trace = Popen([\'ping \' + \'-c 2 \'+ str(session.vars.ipaddress)], stdout=PIPE).communicate()[0]\n        output_of_traceroute = trace.read()\n        session.vars = trace\n        print(session.vars)\n        #trace.close()\n        redirect(URL(\'traceroute_output\'))\n    elif form.errors:\n        response.flash = \'Input has errors\'\n    else:\n        response.flash = \'Please enter a valid IPv4 address.\'\n    #welcome_message_traceroute = "Welcome to the TRACEROUTE Tool!"\n    return dict(form=form)\n\n\n@auth.requires_login()\ndef traceroute_output():\n    return dict(output=session.vars)\n\n\n@auth.requires_login()\ndef whois():\n    welcome_message_whois = "Welcome to the WHOIS Tool!"\n    return dict(message=welcome_message_whois)\n\n\ndef error():\n    error_message = "Ooooops, I am sorry....something went terribly wrong.....please try again."\n    return dict(message=error_message)\n\nresponse._vars=response._caller(traceroute)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/ubuntu/webnettools/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/ubuntu/webnettools/web2py/applications/ssllabs/controllers/tools.py", line 85, in <module>\n  File "/home/ubuntu/webnettools/web2py/gluon/globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/ubuntu/webnettools/web2py/gluon/tools.py", line 4241, in f\n    return action(*a, **b)\n  File "/home/ubuntu/webnettools/web2py/applications/ssllabs/controllers/tools.py", line 56, in traceroute\n    trace = Popen([\'ping \' + \'-c 2 \'+ str(session.vars.ipaddress)], stdout=PIPE).communicate()[0]\n  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__\n    errread, errwrite)\n  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory\n'
p11
s.